# Generated by Django 5.2.17 on 2026-09-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='duckies_inv_ducky_i_b17c39_idx',
            old_name='duckies_inv_ducky_i_5bcd0e_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='duckies_ite_item_ty_819b7b_idx',
            old_name='duckies_ite_item_ty_0f9b76_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='duckies_ite_rarity_d1f554_idx',
            old_name='duckies_ite_rarity_5d7a8e_idx',
        ),
    ]
