# Generated by Django 5.2.17 on 2026-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckies', '0003_item_category_set_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='duckies_ite_categor_350409_idx',
            old_name='duckies_ite_categor_5e5d4c_idx',
        ),
    ]
