# Generated by Django 5.2.17 on 2026-09-10 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckies', '0004_rename_duckies_ite_categor_5e5d4c_idx_duckies_ite_categor_350409_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('family', models.CharField(choices=[('LOCK', 'Bloqueo'), ('INTERFERENCE', 'Interferencia'), ('DELAY', 'Retraso'), ('SABOTAGE', 'Sabotaje'), ('CONTROL', 'Control'), ('COMBO', 'Combo')], max_length=20)),
                ('effect', models.CharField(choices=[('LOCK', 'Bloquear acción'), ('FREEZE', 'Congelar progreso'), ('SILENCE', 'Bloquear habilidad'), ('SCRAMBLE', 'Alterar desafío'), ('FOG', 'Ocultar código'), ('DELAY', 'Retrasar siguiente desafío'), ('SLOW', 'Reducir progreso'), ('PUZZLE', 'Desafío de escape'), ('RESET', 'Romper combo'), ('STACK', 'Acumular debuff'), ('REDIRECT', 'Cambiar ruta'), ('WALL', 'Bloquear avance')], max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Común'), ('RARE', 'Raro'), ('EPIC', 'Épico'), ('LEGENDARY', 'Legendario')], max_length=20)),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, help_text='Duración temporal del efecto; vacío si requiere un desafío.', null=True)),
                ('cooldown_seconds', models.PositiveSmallIntegerField(default=20)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activation_challenge', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=30)),
                ('required_set', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['family', 'price', 'name'],
                'indexes': [models.Index(fields=['family', 'is_active'], name='duckies_att_family_af0fc0_idx'), models.Index(fields=['is_active', 'price'], name='duckies_att_is_acti_c3b17a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttackInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_inventory', to=settings.AUTH_USER_MODEL)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='duckies.attackitem')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'attack'], name='duckies_att_owner_i_cbb9e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'attack'), name='unique_attack_per_player')],
            },
        ),
    ]
