# Generated by Django 5.2.17 on 2026-09-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckies', '0005_attack_image'),
        ('duckies', '0005_attackitem_attackinventory'),
    ]

    operations = [
    ]
